apps/eddyweb/web/router.ex
defmodule Eddyweb.Router do
  use Eddyweb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Eddyweb.Authentication
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", Eddyweb do
    pipe_through :browser # Use the default browser stack

    get "/users", SessionController, :index
    get "/register", SessionController, :new
    post "/register", SessionController, :create
    get "/signin", SessionController, :signin_new
    post "/signin", SessionController, :signin_create
    get "/signout", SessionController, :signout
    get "/changepwd", SessionController, :chgpwd_new
    post "/changepwd", SessionController, :chgpwd_create

    # oAuth
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :oAuth_callback
    post "/:provider/callback", SessionController, :oAuth_callback

  end

  scope "/", Eddyweb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/videos", VideoController
    get "/all-videos", VideoController, :all_videos
    get "/watch/:id/", WatchController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Eddyweb do
  #   pipe_through :api
  # end
end

apps/eddyweb/web/controllers/video_controller.ex
defmodule Eddyweb.VideoController do
  use Eddyweb.Web, :controller
  require Logger

  alias Vroom.{Video, Category}

  plug :require_authenticated when action in [:new, :create]
  plug :load_categories when action in [:new, :create, :edit, :update]

  def index(conn, _params) do
    videos = Vroom.videos(get_session(conn, :user_id))
    render conn, "index.html", videos: videos
  end

  def all_videos(conn, _params) do
    videos = Vroom.videos()
    render conn, "index.html", videos: videos
  end

  def new(conn, _params) do
    changeset = Video.changeset(%Video{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"video" => params}) do
    params = Map.put(params, "user_id", get_session(conn, :user_id))
    Logger.warn "#{inspect(params)}"
    conn
    |> handle_add_video(Vroom.add_video(params))
  end

  def show(conn, %{"id" => id}) do
    video = Vroom.Repo.get(Video, id)
    render conn, "show.html", video: video
  end

  def delete(conn, %{"id" => id}) do
    video = Vroom.Repo.get(Video, id)
    Vroom.Repo.delete!(video)
    conn
    |> put_flash(:info, "Video successfully deleted")
    |> redirect(to: video_path(conn, :index))
  end

  def edit(conn, %{"id" => id}) do
    video = Vroom.Repo.get!(Video, id)
    changeset = Video.changeset(video)
    render conn, "edit.html", video: video, changeset: changeset
  end

  def update(conn, %{"id" => id, "video" => video_params}) do
     video = Vroom.Repo.get(Video, id)
     changeset = Video.changeset(video, video_params)
     handle_update_video(conn, Vroom.Repo.update(changeset))
  end

  defp handle_add_video(conn, {:ok, _}) do
    conn
    |> put_flash(:info, "Video added successfully")
    |> redirect(to: video_path(conn, :index))
  end
  defp handle_add_video(conn, {:error, changeset}) do
    conn
    |> render("new.html", changeset: changeset)
  end
  defp handle_update_video(conn, {:ok, _}) do
    conn
    |> put_flash(:info, "Video updated successfully")
    |> redirect(to: video_path(conn, :index))
  end

  defp handle_update_video(conn, {:error, changeset}) do
    conn
    |> render("edit.html", changeset: changeset)
  end

  defp load_categories(conn, _) do
    query =
      Category
      |> Category.alphabetical
      |> Category.names_and_ids
    categories = Vroom.Repo.all query
    assign(conn, :categories, categories)
  end

end

apps/eddyweb/web/views/video_view.ex
defmodule Eddyweb.VideoView do
  use Eddyweb.Web, :view
end

apps/eddyweb/web/templates/video/edit.html.eex
<h2>Edit Video</h2>

<%= render "form.html", changeset: @changeset, categories: @categories,
                        action: video_path(@conn, :update, @video),
                        type: "edit" %>

<%= link "Back", to: video_path(@conn, :index) %>

apps/eddyweb/web/templates/video/form.html.eex
<div class="container">

  <%= form_for @changeset, @action, [as: :video], fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="form-group">
      <%= label f, :name, class: "control-label" %>
      <%= text_input f, :name, class: "form-control" %>
      <%= error_tag f, :name %>
    </div>

    <div class="form-group">
      <%= label f, :url, class: "control-label" %>
      <%= text_input f, :url, class: "form-control" %>
      <%= error_tag f, :url %>
    </div>

    <div class="form-group">
      <%= label f, :category_id, class: "control-label" %>
      <%= select f, :category_id, @categories,
            class: "form-control", prompt: "Choose a category" %>
    </div>


    <div class="form-group">
      <%= label f, :description, class: "control-label" %>
      <%= text_input f, :description, class: "form-control" %>
      <%= error_tag f, :description %>
    </div>

    <div class="form-group">
      <%= submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

apps/eddyweb/web/templates/video/index.html.eex
<div class="no-container-margins">
  <h2>Listing Videos</h2>

  <table class="table highlight responsive-table table-fixed">
    <thead>
      <tr>
        <th width="10%">User</th>
        <th width="20%">Name</th>
        <th width="20%">URL</th>
        <th width="40%">Description</th>
        <th width="10%">Action</th>
      </tr>
    </thead>
    <tbody>
  <%= for video <- @videos do %>
      <tr class="cell-word-wrap">
        <td><%= video.user_id %></td>
        <td><%= video.name %></td>
        <td><%= video.url %></td>
        <td><%= video.description %></td>
        <td class="highlight">
          <%= link to: watch_path(@conn, :show, video), class: "btn btn-default btn-xs" do %>
            <i class="material-icons">remove_red_eye</i>
          <% end %>
          <%= link to: video_path(@conn, :edit, video), class: "btn btn-default btn-xs" do %>
            <i class="material-icons">mode_edit</i>
          <% end %>
          <%= link to: video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" do %>
            <i class="material-icons">mode_edit</i>
          <% end %>
        </td>

      </tr>
  <% end %>
    </tbody>
  </table>

  <%= link "New video", to: video_path(@conn, :new) %>
</div>

apps/eddyweb/web/templates/video/new.html.eex
<h2>New Video</h2>

<%= render "form.html", changeset: @changeset, categories: @categories,
                        action: video_path(@conn, :create),
                        type: "new" %>

<%= link "Back", to:  video_path(@conn, :index) %>

apps/eddyweb/web/templates/video/show.html.eex
<div class="container">
  <h2>Show Video</h2>

  <ul>

    <li>
      <strong>Name:</strong>
      <%= @video.name %>
    </li>
    <li>
      <strong>URL:</strong>
      <%= @video.url %>
    </li>
    <li>
      <strong>Description:</strong>
      <%= @video.description %>
    </li>

  </ul>

  <%= link "Edit", to: video_path(@conn, :edit, @video) %>
  <%= link "Back", to: video_path(@conn, :index) %>
</div>