apps/eddyweb/web/router.ex
defmodule Eddyweb.Router do
  use Eddyweb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Eddyweb.Authentication
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", Eddyweb do
    pipe_through :browser # Use the default browser stack

    get "/users", SessionController, :index
    get "/register", SessionController, :new
    post "/register", SessionController, :create
    get "/signin", SessionController, :signin_new
    post "/signin", SessionController, :signin_create
    get "/signout", SessionController, :signout
    get "/changepwd", SessionController, :chgpwd_new
    post "/changepwd", SessionController, :chgpwd_create

    # oAuth
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :oAuth_callback
    post "/:provider/callback", SessionController, :oAuth_callback

  end

  scope "/", Eddyweb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/videos", VideoController
    get "/all-videos", VideoController, :all_videos
    get "/watch/:id/", WatchController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Eddyweb do
  #   pipe_through :api
  # end
end

apps/eddyweb/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: if @current_user, do: @current_user.email, else: "Eddy!" %></h2>
  <p class="lead">edu</p>

  <ul>
    <li>
      <%= link "Users", to: session_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Videos", to: video_path(@conn, :index) %>
    </li>

    <li>
      <%= link "All Videos", to: video_path(@conn, :all_videos) %>
    </li>

  </ul>

</div>